# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: gcc

stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

before_script:
     - apt update && apt -y install cmake libgpgme-dev libgcrypt-dev libfuse-dev makepasswd encfs python3-pgpdump opensc-pkcs11 libc6-dev pcscd automake libpcsclite-dev libgtk-3-dev libcriterion-dev
     - ln -s /usr/lib/x86_64-linux-gnu/libopensc.so.7.0.0 /usr/lib/x86_64-linux-gnu/libopensc.so

build:
  stage: build
  script:
    - cd build
    - cmake ..
    - make install

  artifacts:
    paths:
      - build/bin
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    key: build-cache
    paths:
      - build/

# run tests using the binary built before
test:
  stage: test
  script:
    - cd build
    - make test
  cache:
    key: build-cache
    paths:
      - build/

code_quality:
  before_script:
    - ''
  stage: test
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
