#!/bin/bash

#These values are filled in by configuration.sh
MOUNTPOINT=
ENCRYPTED_DIRECTORY_ENCFS=
DECRYPTED_DIRECTORY_ENCFS=
CMAKE_INSTALL_FULL_BINDIR=
CMAKE_INSTALL_FULL_LIBDIR=

mkdir -p $MOUNTPOINT $ENCRYPTED_DIRECTORY_ENCFS $DECRYPTED_DIRECTORY_ENCFS

LD_LIBRARY_PATH=$CMAKE_INSTALL_FULL_LIBDIR:$LD_LIBRARY_PATH $CMAKE_INSTALL_FULL_BINDIR/fuseecs -f -o allow_other $MOUNTPOINT
